POST http://localhost:8080/products
Content-Type: application/json

{

     "name": "Cutting Disc",
   "description": "Aluminium Oxide Cutting Disc, 115mm x 1mm Thick, P60 Grit, BDX, 5 in pack",
   "price": "£8.25"
}

###

GET http://localhost:8080/products/
###

Put http://localhost:8080/products/65294279-5580-4a6e-bbc1-fa953d61886a
Content-Type: application/json

{

  "name": "Cutting Disc",
  "description": "Aluminium Oxide Cutting Disc, 115mm x 1mm Thick, P60 Grit, BDX, 5 in pack",
  "price": "£10.25"
}


